### ISSUE TITLE
JWE encoding by A256GCMKW

### ISSUE THREAD

**Issue by sorokadima** [potatosalad/ruby-jose#13]
Thanks for develop this Gem @potatosalad.
I'm trying to encode a payload by JWE using A256GCMKW algorithm and encoding A256GCM.
I should use a random Content Encryption Key generated from SHA-256 digest of the shared secret.

I have example of realization on JavaScript. But my Ruby code doesn't work as well.

My code (does not work):

```ruby
require 'jose'

payload  = 'The quick brown fox jumps over the lazy dog.'
shared_secret = 'asdfgasdfgasdfgasdfgasdfgasdfgasdfgasdfg'
digest = Digest::SHA2.new(256).hexdigest(shared_secret)
key = JOSE::JWK.from_oct(digest)
encrypted = JOSE::JWE.block_encrypt(key, payload, {
    "alg" => "A256GCMKW",
    "enc" => "A256GCM"
}).compact

puts encrypted
# eyJhbGciOiJBMjU2R0NNS1ciLCJlbmMiOiJBMjU2R0NNIiwiaXYiOiJ2U05QSlVMODZFdjE0dkNrIiwidGFnIjoidWRuM1dHbWRDZ3lHaFpkdUpMVlZJdyJ9.FF3pRkadxVR2x_OtDGr5ofzyhXQe2oIgOpGYDlwW_Q0.dp_h_VbZQ41qN075.18eQ_pKL1uGCeSAy4kdVnoltnDhqzYNv1b555_p8TdfOe-d2fpkl9e6v5Jo.TX4FCa3xD6FnXBz2HZD9tA
```

JS exapmle (works good):

```javascript
const jose = require('jose')
const crypto = require('crypto')
const shared_secret = 'asdfgasdfgasdfgasdfgasdfgasdfgasdfgasdfg';
const digest = crypto.createHash('sha256').update(shared_secret).digest();

const key = jose.JWK.asKey(digest);
const payload = 'The quick brown fox jumps over the lazy dog.';
const jwe = jose.JWE.encrypt(
    payload, key, {
        alg:'A256GCMKW',
        enc:'A256GCM',
    }
)

console.log(jwe);
// eyJhbGciOiJBMjU2R0NNS1ciLCJlbmMiOiJBMjU2R0NNIiwidGFnIjoiVVhtb0dwbzI5V0o0MHNsWHZXc3FXUSIsIml2IjoiMVk3WWxPYjRTNjB1eVFrMyJ9.T7wX7Dt6WhPPkxUmrHgKLbQ3nscNiJ9laz31cwsPYsk.FbigNoLKXNgT_oKF.Sotu5vgQOcdt7gNA8l1lIUmwa-40z7tHWPb951XGjqemVMqcldaD4p_XhXQ.fVuNdAZDPun7KYjKsx06jw
```

What can be wrong with my realization? Am I generating the decryption key correctly or did I miss something in the docs?

**Comment by xvonabur** [comment]
@sorokadima hi! I'm not an expert, but `key` is definitely source of problem.
In js example you will get this object as a `key`:

```js
OctKey {
  kid: 'J1flZxhB1E1y_3I3-0_6tiNIobiE36pJ3O8kIsVwOWI',
  kty: 'oct'
}
```

But not in ruby. Digging into js library source will give you an answer.  `jose.JWK.asKey` returns `Buffer`. Then this buffer is encoded with `fromBase64(buf.toString('base64'))` in `libe/help/base64url.js` . And this value will be `kid` of your key.

Your ruby example returns hex string as `digest`. So you need to convert this hex to actual string first, then use `Base64.urlsafe_encode64(bytes_str, padding: false)` to get similar output as `kid`.

So, correct ruby example:

```ruby
require 'jose'
require 'base64'

payload  = 'The quick brown fox jumps over the lazy dog.'
shared_secret = 'asdfgasdfgasdfgasdfgasdfgasdfgasdfgasdfg'

digest = Digest::SHA2.new(256).hexdigest(shared_secret)
bytes_str = [digest].pack("H*")
base64_digest = Base64.urlsafe_encode64(bytes_str, padding: false)
key = JOSE::JWK.from({ "k" => base64_digest, "kty" => 'oct' })

encrypted = JOSE::JWE.block_encrypt(key, payload, {
    "alg" => "A256GCMKW",
    "enc" => "A256GCM"
}).compact

puts encrypted
```

**Comment by sorokadima** [comment]
@xvonabur , it was super helpful and solved my problem.  thank you!!!
