### ISSUE TITLE
Compare implementing with python

### ISSUE THREAD

**Issue by kortirso** [potatosalad/ruby-jose#5]
I'm writing gem for mobilepay api.
They have example of realization for python [example](https://github.com/MobilePayDev/MobilePay-Merchant-API-Security/blob/master/RequestExamples/python-example.md)

My realisation is
`payload = (request.uri.to_s + request.body.to_s).encode('UTF-8')`
`payload_sha1 = Digest::SHA1.digest(payload)`
`payload_base64 = Base64.encode64(payload_sha1)`
`jwk = JOSE::JWK.from_pem_file('key.pvk')`
`JOSE::JWS.sign(jwk, payload_base64, { "alg" => "RS256" }).compact`

I compared my results with python and the are differ.
payload_base64 is the same

but on python result is
`eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.SmxZc0lqdkdiQUpEN2FRL1RRelBLWTF4NFBVPQ.Qom5rYLeirKeq9D1ipV0LEr2x8RHsflb5NAVI0pL0DrM2zXjYZF7wGZjFov7DNxVngQPuBW-8jpGVMSaHYDd8Kv-and a lot of signs`
on ruby
`eyJhbGciOiJSUzI1NiJ9.SmxZc0lqdkdiQUpEN2FRL1RRelBLWTF4NFBVPQ.nxPPEounvGaQfBiDYRIGzguJQ30iUtHwBdY8mMpdxo4DBt1nZEKCuwHc-and a lof of signs`

so payload part is the same, protected is differ (there are a lot of additional signs on python, and on ruby it is the same like in examples), and signature is fully differ
What can be wrong?

**Comment by potatosalad** [comment]
The difference between the two protected values can be seen by expanding the tokens from each:

```ruby
# Expand the ruby output:
JOSE::JWS.peek_protected('eyJhbGciOiJSUzI1NiJ9.SmxZc0lqdkdiQUpEN2FRL1RRelBLWTF4NFBVPQ.nxPPEounvGaQfBiDYRIGzguJQ30iUtHwBdY8mMpdxo4DBt1nZEKCuwHc')
# => JOSE::Map["alg" => "RS256"]

# Expand the python output:
JOSE::JWS.peek_protected('eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.SmxZc0lqdkdiQUpEN2FRL1RRelBLWTF4NFBVPQ.Qom5rYLeirKeq9D1ipV0LEr2x8RHsflb5NAVI0pL0DrM2zXjYZF7wGZjFov7DNxVngQPuBW-8jpGVMSaHYDd8Kv')
# => JOSE::Map["alg" => "RS256", "typ" => "JWT"]
```

So the python implementation is adding `{"typ":"JWT"}` to the protected JWS header.  In my opinion (which is based on the [JWS](https://tools.ietf.org/html/rfc7515#section-4.1.9) and [JWT](https://tools.ietf.org/html/rfc7519#section-5.1) specs), this behavior is incorrect.

The contained payload type is _not_ a JWT, but a SHA1 hash of the request URI and body that has been base64 encoded (by the way, you're probably looking for `Base64.strict_encode64` instead of `Base64.encode64`).

If, however, you want it to match the python implementation, you just need to add `{ 'typ' => 'JWT' }` when creating the JWS:

```ruby
payload = 'JlYsIjvGbAJD7aQ/TQzPKY1x4PU='
jwk = JOSE::JWK.from('{"d":"ZxVeQCUgisUD0CSf0ai24x259mGJ_QUCd75E6BWAtzndQ9TfsbKHki4qmqaPHstWKfdzNXQpV3hvVw95yKplgIwEwX_apYK2GyIZPrJAU2oSewcXk3MctwHwW8JrzrnkC3qgv4xYbqxd3dknPy5wO4QZbluI7a1RGxxliepqFQU","dp":"3WxM66xNXJAIWAYANoHEYu9IHv7Qqm2WEUZ95ehFzYdNtmNie85c_Js2E_mwa5Dx2WBcPQ7kEymLWHFVdjfAcw","dq":"GSlZ2w0RiiDtqLMnUKdaamvv59gDB_aB7odWukFtYDpk38yyshFK4eYAcZbH8GIF0ZVoZrxZyEYZbdDFm9otgw","e":"AQAB","kty":"RSA","n":"zwXi4E9VC307Ps0cQFzzIBUQX3u1Nj0zhdijyXNJMKZ4joqdPvzhPvvnP4dURZZOcVbD3GEsE8BihufqSWHBcbOf8BuR9sCKa3MmezfwZ_DFWAZ35CZhFwwsD2KLE1W30X1Ccwnk1YbxzLL3ol-eCQItYKaTpr5aeCNbtZsrhDE","p":"696a2VpnLCzgYWUV06jpvLbqZrLQu0XnSXcwkLJoZDge-1tPOAHNBd0d3EW1HV7D78f3PALZ0pfUkSPdGGSXhw","q":"4LEHBnxFUVOa5gqI8MeiBQkLv2U5PZ7ia9SCyzqN43VY2f-ZQ5D36fw-olB901l6zmfPB84RHTE1VPHsI5KEhw","qi":"a5xNBTzUGfQoTYBaZDWppdBOq9uMcYsmi8Es6-hGnXenKG0FCBxYfjNH_HuFJDyYPBM8dsMfXOQ2cJqtSndAGg"}')

# The difference between the python and ruby version is
# whether the {"typ":"JWT"} key/value is included or not.
jws_ruby   = JOSE::JWS.from({ 'alg' => 'RS256' })
jws_python = JOSE::JWS.from({ 'alg' => 'RS256', 'typ' => 'JWT' })

JOSE::JWS.sign(jwk, payload, jws_ruby).compact
# => "eyJhbGciOiJSUzI1NiJ9.SmxZc0lqdkdiQUpEN2FRL1RRelBLWTF4NFBVPQ.oC0audNZoVdM0Xi0eW_2T9L5kJtAjGAWPHjb9g68CsFtoZmGLtBR24JjvphjFfm9puNlSPKCcjKYPnHqb6N9MJHeL7QYA8EZ6FphzXiwLIv5IJ2rj1ojdItBTGoCAe3HQ0J1L0XThOOvHqFZUxCm3kBqEi3rj1MIWJ6wuGionU0"

JOSE::JWS.sign(jwk, payload, jws_python).compact
# => "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.SmxZc0lqdkdiQUpEN2FRL1RRelBLWTF4NFBVPQ.nx6TjQGd_S7vczvkSavYBcitT1zaKSnfWcCf-jbDc99xwDXO9YW0EY0kgbJjBZL8RfCVwK5H-RoF5_jR5jbO667b76JUodOBC8t1r6wAlhRjQZ95xDpKGJ2lGIH7J_rT7rTSieP4wsxfCPYTPVRyYVgFHrl7O08OrZgHsz4spgw"
```

> so payload part is the same, protected is differ (there are a lot of additional signs on python, and on ruby it is the same like in examples), and signature is fully differ

Anytime the protected header or payload changes, the signature will also change.

**Comment by kortirso** [comment]
Great, thanks
